PUT http://localhost:3333/cattle/update/3
Content-Type: application/json

{
    "code": "TD15",
    "amount_milk": 50,
    "amount_food": 450,
    "weight": 800,
    "birth": "2012-10-06T17:56:23.835Z"
}