PUT http://localhost:3333/cattle/update/1
Content-Type: application/json

{
    "code": "TD20",
    "amount_milk": 35,
    "amount_food": 98,
    "weight": 270,
    "birth": "2023-10-06T17:56:23.835Z"

}